version: '3'
services:
  sms:
   build: './sms'
   ports: 
    - "5002:3000"
  emails: 
   build: './emails'
   ports: 
   - "5004:3000"
  notification:
   build: './notification'
   ports: 
   - "5003:3000"
   depends_on:
   - db
   environment:
   - MONGO_DB_URI='mongodb://db/seamsville'
  db:
   image: mongo:latest
   ports:
     - "27017:27017"
  nginx:
   image: nginx:latest
   ports:
     - "8080:8080"
   volumes:
     - './default.conf:/etc/nginx/conf.d/default.conf'
   depends_on: 
     - emails
     - notification
     - sms